spring:
  application:
    name: vocabjotdown-web-api
  redis:
    host: localhost
    port: 6379
  datasource:
    username: vocabjotdown
    password: Test@123.com
    url: jdbc:mysql://192.168.100.60:3306/vocabjotdown
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
  security:
    basic:
      enabled: false
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 3600
      cookie:
        max-age: 3600
vocabjotdown:
  dictionary-en-service: http://localhost:8081
  dictionary-jp-service: http://localhost:8081
  firebase-database-url: https://vocabjotdown-default-rtdb.firebaseio.com
logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
    com:
      tatsonlambda: DEBUG
  pattern:
    console: "%d{HH:mm:ss} || %highlight(%5p) < %highlight(%-35.35logger{35}) > %highlight(%m%n)"
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

