spring:
  application:
    name: minidict-dictionary-en
  datasource:
    username: vocabjotdown
    password: Test@123.com
    url: jdbc:mysql://192.168.100.60:3306/vocabjotdown
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
server:
  port: 8081
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
